### ISSUE TITLE
More MotionSensor Exceptions in Logs

### ISSUE THREAD

**Issue by jakobyte** [samemory/homebridge-eufy-security#101]
It seems that further exceptions are present in the logs in version 0.2.13. I’m unsure if these issues are related to my previous issue #75 - The configuration and environment above remains the same.

Initially it seems that there is an issue restoring the Homebase:

```
[7/29/2021, 10:58:36 PM] [EufySecurity] Restoring existing accessory from cache: Homebase
(node:1570) UnhandledPromiseRejectionWarning: Error: A Controller with the type/id 'camera' was already added to the accessory Front Door
    at Accessory.configureController (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:742:13)
    at PlatformAccessory.configureController (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:143:34)
    at new DoorbellCameraAccessory (/homebridge/node_modules/homebridge-eufy-security/src/accessories/DoorbellCameraAccessory.ts:146:15)
    at EufySecurityPlatform.register_accessory (/homebridge/node_modules/homebridge-eufy-security/src/platform.ts:278:9)
    at EufySecurityPlatform.discoverDevices (/homebridge/node_modules/homebridge-eufy-security/src/platform.ts:179:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-eufy-security/src/platform.ts:96:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1570) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1570) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

There seems to be some additional issues with the motion sensors:

```
[7/29/2021, 10:59:37 PM] [homebridge-eufy-security] This plugin threw an error from the characteristic 'Event Snapshots Active': Unhandled error thrown inside read handler for characteristic: This callback function has already been called by someone else; it can only be called one time.. See https://git.io/JtMGR for more info.
[7/29/2021, 10:59:37 PM] [homebridge-eufy-security] This plugin threw an error from the characteristic 'HomeKit Camera Active': Unhandled error thrown inside read handler for characteristic: This callback function has already been called by someone else; it can only be called one time.. See https://git.io/JtMGR for more info.
(node:1570) UnhandledPromiseRejectionWarning: TypeError: this.eufyDevice.isMotionDetected is not a function
    at DoorbellCameraAccessory.isMotionDetected (/homebridge/node_modules/homebridge-eufy-security/src/accessories/DoorbellCameraAccessory.ts:250:46)
    at DoorbellCameraAccessory.handleMotionDetectedGet (/homebridge/node_modules/homebridge-eufy-security/src/accessories/DoorbellCameraAccessory.ts:260:37)
    at MotionDetected.emit (events.js:327:22)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at MotionDetected.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
(node:1570) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
```

Plugin Config:

{
"username": "xxxxxxxxxxxx",
"password": "xxxxxxxxxxxxx",
"ipAddress": "192.168.x.x",
"enableDetailedLogging": false,
"hkHome": 1,
"hkAway": 0,
"hkNight": 3,
"hkOff": 63,
"hkDisarmed": 6,
"platform": "EufySecurity"
}

Environment:

Plugin Version: v0.2.13
Homebridge Version: 1.3.4
Node.js Version: v14.15.4
NPM Version: 6.14.10
Operating System: Docker

_Originally posted by @jakobyte in https://github.com/samemory/homebridge-eufy-security/issues/75#issuecomment-889497797_

**Comment by lenoxys** [comment]
#75 reopen
