### ISSUE TITLE
[homebridge-eufy-security] This plugin slows down Homebridge.

### ISSUE THREAD

**Issue by EvoSems** [samemory/homebridge-eufy-security#107]
Does this mean I cannot use both Eufy and HomeKit App at the same time? My Pi4 is running super slow since installing this plugin too. assume its related to this error

My user case is. having there HomeKit stream in PIP on the Apple TV watching the baby sleep. but also having the eufy app for Crying Alerts etc and 2k feed on my phone.

[01/08/2021, 09:31:41] [homebridge-eufy-security] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[01/08/2021, 09:31:41] [homebridge-eufy-security] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[01/08/2021, 09:31:44] [RPi] RaspberryPi4: set Load from 1.73 to 1.72
[01/08/2021, 09:31:47] [homebridge-eufy-security] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[01/08/2021, 09:31:47] [homebridge-eufy-security] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[01/08/2021, 09:31:50] [homebridge-eufy-security] This plugin threw an error from the characteristic 'Event Snapshots Active': Unhandled error thrown inside read handler for characteristic: This callback function has already been called by someone else; it can only be called one time.. See https://git.io/JtMGR for more info.
[01/08/2021, 09:31:50] [homebridge-eufy-security] This plugin threw an error from the characteristic 'HomeKit Camera Active': Unhandled error thrown inside read handler for characteristic: This callback function has already been called by someone else; it can only be called one time.. See https://git.io/JtMGR for more info.

**Comment by EvoSems** [comment]
https://github.com/homebridge/homebridge/wiki/Characteristic-Warnings

**Comment by EvoSems** [comment]
(node:6031) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at CameraAccessory.handleOnGet (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:310:53)
    at On.emit (events.js:400:28)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
(node:6031) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:6031) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at CameraAccessory.handleMotionOnGet (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:336:74)
    at On.emit (events.js:400:28)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
(node:6031) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)

**Comment by schliemann** [comment]
Can you describe your setup? Which devices do you have?

**Comment by schliemann** [comment]
Mine is running on a PI4 as well and I use the eufy app and don't get this slow down error.

**Comment by EvoSems** [comment]
I have 
Floodlight Cam
Indoor Cam 2k
Eufy cam pro 2 x 2 with Homebase 2

My Pi is new install of Pi lite. I also have hyperhdr installed.

**Comment by schliemann** [comment]
What version of the plugin are you using?

**Comment by EvoSems** [comment]
0.2.13
Thanks for your help mate.

**Comment by xraywinedrinker** [comment]
I had the same slowdown issue with my 2C and indoor 2K cameras. After I removed the indoor cameras the slowdown error was eliminated.

**Comment by lenoxys** [comment]
Did you create another account for homebridge plugin ?
See this article : https://support.eufylife.com/s/article/Share-Your-eufySecurity-Devices-With-Your-Family

I know in the past sharing the same account with the EufyApp and Homebridge one could implies some issue.

**Comment by xraywinedrinker** [comment]
I do use a guest account for eufy homebridge.

**Comment by lenoxys** [comment]
Do you mind if you can share with admin rights to this account: eufy-plugin-test@secugrator.com.

it will more easy for me to dig in. At least to confirm it's an hardware issue or plugin one. I will let you know when you can revoke the access.
https://support.eufylife.com/s/article/Share-Your-eufySecurity-Devices-With-Your-Family

**Comment by EvoSems** [comment]
Yes I do have a seperate account for homebridge use. 

I have set the plug-in up as a child bridge for now as it was slowing the rest of homebridge down. 

Interesting. I mainly only want the indoor cam in HomeKit. As I can watch the baby sleep in PIP mode on the Apple TV.

**Comment by EvoSems** [comment]
latest log

[02/08/2021, 21:35:38] [homebridge-eufy-security] Back Yard has a camera
[02/08/2021, 21:35:38] [homebridge-eufy-security] Restoring existing accessory from cache: Back Yard
[02/08/2021, 21:35:38] [homebridge-eufy-security] Front Yard has a camera
[02/08/2021, 21:35:38] [homebridge-eufy-security] Restoring existing accessory from cache: Front Yard
[02/08/2021, 21:35:38] [homebridge-eufy-security] Cali Bedroom has a camera
[02/08/2021, 21:35:38] [homebridge-eufy-security] Restoring existing accessory from cache: Cali Bedroom
[02/08/2021, 21:35:38] [homebridge-eufy-security] Carport has a camera
[02/08/2021, 21:35:38] [homebridge-eufy-security] Restoring existing accessory from cache: Carport
[02/08/2021, 21:35:38] [homebridge-eufy-security] Restoring existing accessory from cache: Home
[02/08/2021, 21:35:38] [homebridge-eufy-security] Cali Bedroom has a camera
(node:9733) UnhandledPromiseRejectionWarning: Error: A Controller with the type/id 'camera' was already added to the accessory Cali Bedroom
    at Accessory.configureController (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:742:13)
    at PlatformAccessory.configureController (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:143:34)
    at new CameraAccessory (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:70:17)
    at EufySecurityPlatform.register_accessory (/usr/lib/node_modules/homebridge-eufy-security/src/platform.ts:273:9)
    at EufySecurityPlatform.discoverDevices (/usr/lib/node_modules/homebridge-eufy-security/src/platform.ts:179:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/homebridge-eufy-security/src/platform.ts:96:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9733) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by lenoxys** [comment]
Can you test 0.3.8 version ?

**Comment by EvoSems** [comment]
0.3.8 seems to correct the issue. Many thanks

**Comment by lenoxys** [comment]
Cool thanks for your feedback!
