### ISSUE TITLE
UnhandledPromiseRejectionWarning & Non-Working Doorbell Camera

### ISSUE THREAD

**Issue by PSedd** [samemory/homebridge-eufy-security#133]
**Describe The Bug:**
Camera (Wired 2K) does not stream. In HomeKit the device shows as a "No Response". Was working fine until about 2-3 weeks ago. Plugin is on child bridge due to "this plugin slows down homebridge" message the last few weeks. 

**To Reproduce:**
Just use device, all functionality is broken for me. 

**Expected behavior:**
Stream video, show alerts when door bell is rung, etc

**Logs:**

```
(node:32715) UnhandledPromiseRejectionWarning: TypeError: this.eufyDevice.isMotionDetected is not a function
    at DoorbellCameraAccessory.isMotionDetected (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/DoorbellCameraAccessory.ts:250:46)
    at DoorbellCameraAccessory.handleMotionDetectedGet (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/DoorbellCameraAccessory.ts:260:37)
    at MotionDetected.emit (events.js:400:28)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at MotionDetected.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
(node:32715) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 26)
[Doorbell] Unhandled error thrown inside snapshot request handler: TypeError: this.device.getLastCameraImageURL is not a function
    at EufyCameraStreamingDelegate.handleSnapshotRequest (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/streamingDelegate.ts:212:42)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:436:23
    at new Promise (<anonymous>)
    at CameraController.handleSnapshotRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:420:12)
    at Bridge.Accessory.handleResource (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1781:18)
    at HAPServer.emit (events.js:400:28)
    at HAPServer.handleResource (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:968:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:369:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
(node:32715) UnhandledPromiseRejectionWarning: TypeError: this.eufyDevice.isMotionDetected is not a function
    at DoorbellCameraAccessory.isMotionDetected (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/DoorbellCameraAccessory.ts:250:46)
    at DoorbellCameraAccessory.handleMotionDetectedGet (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/DoorbellCameraAccessory.ts:260:37)
    at MotionDetected.emit (events.js:400:28)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at MotionDetected.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
(node:32715) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 29)
[Doorbell] Unhandled error thrown inside snapshot request handler: TypeError: this.device.getLastCameraImageURL is not a function
    at EufyCameraStreamingDelegate.handleSnapshotRequest (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/streamingDelegate.ts:212:42)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:436:23
    at new Promise (<anonymous>)
    at CameraController.handleSnapshotRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:420:12)
    at Bridge.Accessory.handleResource (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1781:18)
    at HAPServer.emit (events.js:400:28)
    at HAPServer.handleResource (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:968:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:369:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
(node:32715) UnhandledPromiseRejectionWarning: TypeError: this.device.startStream is not a function
    at EufyCameraStreamingDelegate.startStream (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/streamingDelegate.ts:349:37)
    at EufyCameraStreamingDelegate.handleStreamRequest (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/streamingDelegate.ts:559:16)
    at RTPStreamManagement._handleStartStream (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:816:19)
    at RTPStreamManagement._handleSelectedStreamConfigurationWrite (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:647:14)
    at SelectedRTPStreamConfiguration.emit (events.js:400:28)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1632:16
    at new Promise (<anonymous>)
    at SelectedRTPStreamConfiguration.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1630:14)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
(node:32715) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 31)
(node:32715) UnhandledPromiseRejectionWarning: TypeError: this.eufyDevice.isMotionDetected is not a function
    at DoorbellCameraAccessory.isMotionDetected (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/DoorbellCameraAccessory.ts:250:46)
    at DoorbellCameraAccessory.handleMotionDetectedGet (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/DoorbellCameraAccessory.ts:260:37)
    at MotionDetected.emit (events.js:400:28)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at MotionDetected.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
(node:32715) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 33)
[8/4/2021, 4:56:12 AM] [homebridge-eufy-security] Stopped video stream. Doorbell
[8/4/2021, 4:56:12 AM] [homebridge-eufy-security] This plugin threw an error from the characteristic 'Selected RTP Stream Configuration': Unhandled error thrown inside write handler for characteristic: this.device.stopStream is not a function. See https://git.io/JtMGR for more info.
[Doorbell] Unhandled error thrown inside snapshot request handler: TypeError: this.device.getLastCameraImageURL is not a function
    at EufyCameraStreamingDelegate.handleSnapshotRequest (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/streamingDelegate.ts:212:42)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:436:23
    at new Promise (<anonymous>)
    at CameraController.handleSnapshotRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:420:12)
    at Bridge.Accessory.handleResource (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1781:18)
    at HAPServer.emit (events.js:400:28)
    at HAPServer.handleResource (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:968:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:369:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
[Doorbell] Unhandled error thrown inside snapshot request handler: TypeError: this.device.getLastCameraImageURL is not a function
    at EufyCameraStreamingDelegate.handleSnapshotRequest (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/streamingDelegate.ts:212:42)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:436:23
    at new Promise (<anonymous>)
    at CameraController.handleSnapshotRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:420:12)
    at Bridge.Accessory.handleResource (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1781:18)
    at HAPServer.emit (events.js:400:28)
    at HAPServer.handleResource (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:968:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:369:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
```

**Plugin Config:**

```json
{
    "username": "REDACTED@gmail.com",
    "password": "REDACTED",
    "enableDetailedLogging": true,
    "hkHome": 1,
    "hkAway": 0,
    "hkNight": 3,
    "hkOff": 63,
    "hkDisarmed": 6,
    "_bridge": {
        "username": "0E:C2:7A:FA:3C:A4",
        "port": 31939
    },
    "platform": "EufySecurity"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: homebridge-eufy-security v0.2.13 
* **Homebridge Version**: v1.3.4 
* **Node.js Version**:  v14.17.4
* **NPM Version**:  6.14.14
* **Operating System**:  Ubuntu 20.04.2 LTS

**Comment by lenoxys** [comment]
hello, can you test on dev ? https://github.com/samemory/homebridge-eufy-security/wiki/How-to-switch-on-dev-branch

**Comment by PSedd** [comment]
Move up to Dev, the overall stability seems better, and I have the other cameras (5 2C Pros) in now which is cool. However, my doorbell has completely vanished from the plugin. I removed the cached item as I was still having issues and figured a clean upgrade would be better, but it's just gone! Doesn't even show as a discovered device, which is strange.

I'll give it a few days and see if it's back, but we can consider this closed as the latest Dev version fixed the above issue.
