### ISSUE TITLE
Camera motion switch removed in 3.14 beta

### ISSUE THREAD

**Issue by xraywinedrinker** [samemory/homebridge-eufy-security#144]
The current stable version provides the ability to turn motion on and off on the Homebase-based cameras (2C for me) but I see that the latest dev has removed this feature. 

Any chance to return this feature?

**Comment by lenoxys** [comment]
Able to reproduced still digging why

**Comment by lenoxys** [comment]
can you test ?

**Comment by xraywinedrinker** [comment]
This is great! Running beta 0.3.21 I now have controls to disable motion sensors and turning the cameras on/off AND changing security modes in 2C cameras AND indoor 2k.
There is a small error showing issue with detecting the battery percentage on the wired indoor 2k camera. 

Partial log: [8/11/2021, 8:32:53 AM] [EufySecurity] HomeBase Triggered GET SecuritySystemCurrentState
[8/11/2021, 8:32:53 AM] [EufySecurity] Connected to Eufy API
[8/11/2021, 8:32:53 AM] [EufySecurity] Eufy Guard Mode:  { value: 63, timestamp: 1628695787238 }
[8/11/2021, 8:32:53 AM] [EufySecurity] HomeBase Triggered GET SecuritySystemTargetState
[8/11/2021, 8:32:53 AM] [EufySecurity] Connected to Eufy API
[8/11/2021, 8:32:53 AM] [EufySecurity] Eufy Guard Mode:  { value: 63, timestamp: 1628695787238 }
[8/11/2021, 8:32:53 AM] [EufySecurity] Driveway Triggered GET Enable: true
[8/11/2021, 8:32:53 AM] [EufySecurity] Backyard Triggered GET Enable: true
[8/11/2021, 8:32:53 AM] [EufySecurity] Front Door Triggered GET Enable: true
[8/11/2021, 8:32:53 AM] [EufySecurity] Front Yard Triggered GET Enable: true
[8/11/2021, 8:32:53 AM] [EufySecurity] Kitchen Triggered GET Enable: false
[8/11/2021, 8:32:53 AM] [EufySecurity] Kitchen Triggered GET SecuritySystemCurrentState
[8/11/2021, 8:32:53 AM] [EufySecurity] Connected to Eufy API
[8/11/2021, 8:32:53 AM] [EufySecurity] Eufy Guard Mode:  { value: 63, timestamp: 1628695782000 }
[8/11/2021, 8:32:53 AM] [EufySecurity] Kitchen Triggered GET SecuritySystemTargetState
[8/11/2021, 8:32:53 AM] [EufySecurity] Connected to Eufy API
[8/11/2021, 8:32:53 AM] [EufySecurity] Eufy Guard Mode:  { value: 63, timestamp: 1628695782000 }
[8/11/2021, 8:32:53 AM] [EufySecurity] HomeBase Handle Current System state:  --  3
[8/11/2021, 8:32:53 AM] [EufySecurity] Driveway Triggered GET MotionDetected: false
[8/11/2021, 8:32:53 AM] [EufySecurity] Driveway Triggered GET BatteryLevel: 80
[8/11/2021, 8:32:53 AM] [EufySecurity] Driveway Triggered GET Motion: false
[8/11/2021, 8:32:53 AM] [EufySecurity] Backyard Triggered GET MotionDetected: false
[8/11/2021, 8:32:53 AM] [EufySecurity] Backyard Triggered GET BatteryLevel: 100
[8/11/2021, 8:32:53 AM] [EufySecurity] Backyard Triggered GET Motion: false
[8/11/2021, 8:32:53 AM] [EufySecurity] Front Door Triggered GET MotionDetected: false
[8/11/2021, 8:32:53 AM] [EufySecurity] Front Door Triggered GET BatteryLevel: 85
[8/11/2021, 8:32:53 AM] [EufySecurity] Front Door Triggered GET Motion: false
[8/11/2021, 8:32:53 AM] [EufySecurity] Front Yard Triggered GET MotionDetected: false
[8/11/2021, 8:32:53 AM] [EufySecurity] Front Yard Triggered GET BatteryLevel: 90
[8/11/2021, 8:32:53 AM] [EufySecurity] Front Yard Triggered GET Motion: false
[8/11/2021, 8:32:53 AM] [EufySecurity] Kitchen Triggered GET MotionDetected: false
[8/11/2021, 8:32:53 AM] [EufySecurity] Kitchen Triggered GET Motion: false
[8/11/2021, 8:32:53 AM] [EufySecurity] Kitchen Handle Current System state:  --  3
[8/11/2021, 8:32:53 AM] [homebridge-eufy-security] This plugin threw an error from the characteristic 'Battery Level': Unhandled error thrown inside read handler for characteristic: Cannot read property 'value' of undefined. See https://git.io/JtMGR for more info.
[8/11/2021, 8:32:53 AM] [homebridge-eufy-security] TypeError: Cannot read property 'value' of undefined
    at CameraAccessory.getCurrentBatteryLevel (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:209:25)
    at CameraAccessory.handleBatteryLevelGet (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:216:37)
    at BatteryLevel.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1450:32)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at BatteryLevel.Characteristic.handleGetRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:656:24)
    at BatteryLevel.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2103:22)
[8/11/2021, 8:33:08 AM] [EufySecurity] PollingInterval: 10
[8/11/2021, 8:33:08 AM] [EufySecurity] Refresh data from cloud and schedule next refresh.

**Comment by xraywinedrinker** [comment]
I’m closing as my original issue has been resolved. Thank you!
