### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by aeppert** [samemory/homebridge-eufy-security#208]
### What happened?

Configured the homebridge-eufy-security plugin correct, it connects, seems to enumerate the devices then fails with an indexOf error.

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Raspbian

### Relevant log output

```shell
8/25/2021, 9:42:59 AM [8/25/2021, 1:42:59 PM] [EufySecurity-1.0.0-rc.8] DEBUG: Found 1 stations.
8/25/2021, 9:42:59 AM [8/25/2021, 1:42:59 PM] [EufySecurity-1.0.0-rc.8] DEBUG: Found Station <REDACTED> <REDACTED> Front Door DOORBELL { value: '<REDACTED>', timestamp: 1629892830000 }
8/25/2021, 9:42:59 AM (node:21277) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'indexOf' of undefined
8/25/2021, 9:42:59 AM at EufySecurityPlatform.discoverDevices (/hb/node_modules/homebridge-eufy-security/src/platform.ts:182:38)
8/25/2021, 9:42:59 AM at processTicksAndRejections (internal/process/task_queues.js:93:5)
8/25/2021, 9:42:59 AM at HomebridgeAPI.<anonymous> (/hb/node_modules/homebridge-eufy-security/src/platform.ts:127:7)
8/25/2021, 9:42:59 AM (Use `node --trace-warnings ...` to show where the warning was created)
8/25/2021, 9:42:59 AM (node:21277) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
8/25/2021, 9:42:59 AM (node:21277) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
8/25/2021, 9:43:02 AM [8/25/2021, 1:43:02 PM] [EufySecurity-1.0.0-rc.8] DEBUG: Push Connected!
8/25/2021, 9:43:03 AM [myQ] myQ API: Successfully connected to the myQ API.A bug happened!
```

**Comment by lenoxys** [comment]
Hello!

Within the plugin settings, can you resync by clicking the green button ?

**Comment by lenoxys** [comment]
can you put your config json, here ? Be sure to remove your credentials
