### ISSUE TITLE
[Bug]: can’t login after plug-in remove

### ISSUE THREAD

**Issue by danidindin** [samemory/homebridge-eufy-security#254]
### What happened?

The plug in was working well,
But after I uninstall the plug in and installed again
I can’t login again and cannot get the my camera.

I get the error:
“this.driver.refreshData is not a functional”
Someone was get this error?

What can I do?

Thanks

### Device Type

Doorbell (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v12 (Supported)

### Operating System

Mac OS X

**Comment by charlierushton** [comment]
I am also getting this problem.

I am new to Homebridge so don't really know where to start

Logs:
[10/18/2021, 10:55:42 AM] [EufySecurity] Error refreshing data from Eufy:  TypeError: client.refreshData is not a function
    at EufySecurityPlatform.refreshData (/opt/homebrew/lib/node_modules/homebridge-eufy-security/src/platform.ts:418:22)
    at EufySecurityPlatform.discoverDevices (/opt/homebrew/lib/node_modules/homebridge-eufy-security/src/platform.ts:151:16)
    at HomebridgeAPI.<anonymous> (/opt/homebrew/lib/node_modules/homebridge-eufy-security/src/platform.ts:119:7)

**Comment by charlierushton** [comment]
I use the same account as in the eufy app @lenoxys

**Comment by charlierushton** [comment]
I also created a separate account / guest user and tried that, didn't work
