### ISSUE TITLE
[Bug]: unable to see devices after update

### ISSUE THREAD

**Issue by xixihahajeff** [samemory/homebridge-eufy-security#259]
### What happened?

I am unable to see all my eufy devices after updating my Hoobs hardware. Please advise. Thanks.

### Device Type

other (UnSupported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

other (UnSupported)

### NodeJS Version

v14 (Supported)

### Operating System

Raspbian

### Relevant log output

```shell
19/10/2021, 1:17:09 PMeufysecuritybridge stopping
19/10/2021, 1:17:13 PMEufy Security Bridge starting
19/10/2021, 1:17:23 PMEufy Security BridgeLoaded plugin 'homebridge-eufy-security'
19/10/2021, 1:17:23 PMEufy Security BridgeLoading 1 platforms...
19/10/2021, 1:17:23 PMEufy Security BridgeEufySecurityFinished initializing Eufy Security Platform
19/10/2021, 1:17:23 PMEufy Security BridgeEufySecurityERRORError refreshing data from Eufy:  TypeError: client.refreshData is not a function
    at EufySecurityPlatform.refreshData (/var/lib/hoobs/eufysecuritybridge/node_modules/homebridge-eufy-security/src/platform.ts:418:22)
    at EufySecurityPlatform.discoverDevices (/var/lib/hoobs/eufysecuritybridge/node_modules/homebridge-eufy-security/src/platform.ts:151:16)
    at HomebridgeAPI.<anonymous> (/var/lib/hoobs/eufysecuritybridge/node_modules/homebridge-eufy-security/src/platform.ts:119:7)
19/10/2021, 1:17:23 PMEufy Security BridgeBridge is running on port 53826.
```

**Comment by jp-lno** [comment]
Seems to be the same issue as : #263

Try to increase permission on your guest account

**Comment by fenninculus** [comment]
Thanks, problem solved!

**Comment by lenoxys** [comment]
thanks for your feedback. I've updated the doc
