### ISSUE TITLE
Doorbell Camera does not respond

### ISSUE THREAD

**Issue by jasonwfrancis1** [samemory/homebridge-eufy-security#29]
I can only get the doorbell camera to stream intermittently. The majority of the time it times out with the "No Response" image.

This is in the logs:

13/06/2021, 12:18:25 {"name":"eufyLog","hostname":"hoobs","pid":13039,"level":30,"msg":"Livestream of camera T8210P0020500575 started","time":"2021-06-13T11:18:25.598Z","v":0}
13/06/2021, 12:18:25 [EufySecurity] Starting video stream: 1280 x 720, 30 fps, 299 kbps Front Door
13/06/2021, 12:18:55 [EufySecurity] Stopped video stream. Front Door
13/06/2021, 12:18:55 {"name":"eufyLog","hostname":"hoobs","pid":13039,"level":50,"msg":"Response code not ok { code: 20023, msg: 'Failed to request.' }","time":"2021-06-13T11:18:55.563Z","v":0}

**Comment by jasonwfrancis1** [comment]
I also have these errors when i re-start homebridge

13/06/2021, 12:36:36 [HOOBS 1CBA@HomeKit Camera Active] The write handler for the characteristic 'HomeKit Camera Active' on the accessory 'Front Door' didn't respond at all!. Please check that you properly call the callback!
13/06/2021, 12:36:36 [HOOBS 1CBA@Event Snapshots Active] The write handler for the characteristic 'Event Snapshots Active' on the accessory 'Front Door' didn't respond at all!. Please check that you properly call the callback!

**Comment by jasonwfrancis1** [comment]
{"name":"eufyLog","hostname":"hoobs","pid":15475,"level":50,"msg":"Error: Error: read ETIMEDOUT\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {\n  errno: -110,\n  code: 'ETIMEDOUT',\n  syscall: 'read'\n}","time":"2021-06-13T11:39:45.236Z","v":0}

**Comment by javierireyes** [comment]
Hi, I'm also experiencing something very similar, here's the error from the log:
[Doorbell] Unhandled error thrown inside snapshot request handler: TypeError: Cannot read property 'value' of undefined
    at EufyCameraStreamingDelegate.handleSnapshotRequest (/usr/local/lib/node_modules/homebridge-eufy-security/src/streamingDelegate.ts:210:65)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:436:23
    at new Promise (<anonymous>)
    at CameraController.handleSnapshotRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:420:12)
    at Bridge.Accessory.handleResource (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1781:18)
    at HAPServer.emit (events.js:375:28)
    at HAPServer.handleResource (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:968:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:369:11)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)

**Comment by schliemann** [comment]
Please test again with the newest version of the plugin.

**Comment by schliemann** [comment]
@jasonwfrancis1 Please re-test.
