### ISSUE TITLE
[Bug]:  Unable to start livestream

### ISSUE THREAD

**Issue by aididhaiqal** [samemory/homebridge-eufy-security#352]
### What happened?

Hi,

When I am using docker, it appear that the plugin fail to stream due to some permission issue. Any suggestion?

Doorbell_audio Error in NamePipe listen EACCES: permission denied ./4.sock Error: listen EACCES: permission denied ./4.sock
    at Server.setupListenHandle [as _listen2] (node:net:1313:21)
    at listenInCluster (node:net:1378:12)
    at Server.listen (node:net:1476:5)
    at new NamePipeStream (/homebridge/node_modules/homebridge-eufy-security/src/accessories/UniversalStream.ts:54:21)
    at StreamInput (/homebridge/node_modules/homebridge-eufy-security/src/accessories/UniversalStream.ts:83:12)
    at StreamingDelegate.startStream (/homebridge/node_modules/homebridge-eufy-security/src/accessories/streamingDelegate.ts:528:45)
[2/10/2022, 9:57:28 PM] [EufySecurity] Doorbell_audio FFmpeg exited with code: 1 and signal: null (Error)

### Device Type

Doorbell (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Docker (UnSupported)

**Comment by aididhaiqal** [comment]
I somehow managed to fix the above error by setting docker PUID to 0 for root but livestream still not working,

`2/11/2022, 5:35:17 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video     Last message repeated 16 times
[2/11/2022, 5:35:17 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video frame=   35 fps=0.0 q=37.0 size=      47kB time=00:00:01.13 bitrate= 342.6kbits/s dup=17 drop=0 speed=1.45x    
[2/11/2022, 5:35:17 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video Getting the first frames took 2.132 seconds.
[2/11/2022, 5:35:17 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video *** 1 dup!
[2/11/2022, 5:35:17 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video     Last message repeated 10 times
[2/11/2022, 5:35:17 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video frame=   57 fps= 44 q=36.0 size=      67kB time=00:00:01.86 bitrate= 293.0kbits/s dup=28 drop=0 speed=1.43x    
[2/11/2022, 5:35:17 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video *** 1 dup!
[2/11/2022, 5:35:18 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video     Last message repeated 7 times
[2/11/2022, 5:35:18 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video frame=   73 fps= 40 q=35.0 size=      84kB time=00:00:02.40 bitrate= 286.3kbits/s dup=36 drop=0 speed=1.31x    
[2/11/2022, 5:35:18 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video *** 1 dup!
[2/11/2022, 5:35:18 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video     Last message repeated 6 times
[2/11/2022, 5:35:18 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video frame=   87 fps= 37 q=34.0 size=      96kB time=00:00:02.86 bitrate= 273.3kbits/s dup=43 drop=0 speed=1.23x    
[2/11/2022, 5:35:18 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video *** 1 dup!
[2/11/2022, 5:35:19 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video     Last message repeated 7 times
[2/11/2022, 5:35:19 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video frame=  103 fps= 36 q=33.0 size=     111kB time=00:00:03.40 bitrate= 266.5kbits/s dup=51 drop=0 speed=1.19x    
[2/11/2022, 5:35:19 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video *** 1 dup!
[2/11/2022, 5:35:19 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video     Last message repeated 7 times
[2/11/2022, 5:35:19 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video frame=  119 fps= 35 q=31.0 size=     128kB time=00:00:03.93 bitrate= 266.5kbits/s dup=59 drop=0 speed=1.16x    
[2/11/2022, 5:35:19 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video *** 1 dup!
[2/11/2022, 5:35:20 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video     Last message repeated 7 times
[2/11/2022, 5:35:20 PM] [EufySecurity-1.1.1-beta.19] DEBUG: Doorbell_video frame=  135 fps= 34 q=32.0 size=     146kB time=00:00:04.46 bitrate= 267.2kbits/s dup=67 drop=0 speed=1.13x  `

Seems like ffmpeg trying to do something here but the stream on my phone still stuck in the waiting loop

**Comment by karesake** [comment]
Can you install my fork and Test it again ? 

npm install github:karesake/homebridge-eufy-security

**Comment by lenoxys** [comment]
Please use the latest beta. We've fixed docker issue after .26
