### ISSUE TITLE
[Bug]: username and password always wrong

### ISSUE THREAD

**Issue by kisonho** [samemory/homebridge-eufy-security#368]
### What happened?

Cannot login, always showed `Wrong username and password`, while the login info has been verified via official app. 

### Device Type

Contact Sensor (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
Code: 100032
Msg: Failed to request
```

**Comment by kisonho** [comment]
> Did you check this [Common Issues](https://github.com/samemory/homebridge-eufy-security/wiki/Common-Issues) pages ?

Yes, reinstalled and disabled two-factor authentication.

**Comment by alternativ** [comment]
@kisonho, this has to do with the mandatory country selection upon logging in the eufy platform. If you switch to the beta (plugin config -> install previous version -> select the latest beta) you should be able to login :).

**Comment by DolmensDude** [comment]
> this has to do with the mandatory country selection upon logging in the eufy platform. If you switch to the beta (plugin config -> install previous version -> select the latest beta) you should be able to login :).

yeah, I got hit by this yesterday... strange thing is that the eufy security app (plugin) on Homey is not having this problem, but I *prefer* this plugin over HomeBridge.

Issue though is: okay, I can log in, but my two Floodlight Cam Pro 2 and it seems (still) incompatible with this plugin even though it has been out for awhile and the underlying comms plugin says it supports the Floodlight Cam Pro 2's.

I'm stuck on the beta, because it's the only thing that will connect at all, but... I'm offering again - how can I help move the plugin forward??? what's should I do? logfiles? dumps? just let me know the official route.

**Comment by DolmensDude** [comment]
this is what is getting thrown up in the logfile - Wireless Doorbell also raising error and warning messages:

[3/29/2022, 11:38:17 AM] [Meross] ✓ Setup complete. This plugin has been made with ♥ by bwp91 from the UK!
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Exterior North looks station but it's not could imply some errors Type: 38
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Exterior North has no battery
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Exterior North Looks like not compatible with isEnabled or this has been disabled within configuration
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Exterior North Looks like not compatible with isMotionDetectionEnabled or this has been disabled within configuration
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Exterior North Looks like not compatible with DeviceLight
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Exterior West looks station but it's not could imply some errors Type: 38
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Exterior West has no battery
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Exterior West Looks like not compatible with isEnabled or this has been disabled within configuration
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Exterior West Looks like not compatible with isMotionDetectionEnabled or this has been disabled within configuration
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Exterior West Looks like not compatible with DeviceLight
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Doorbell raise error to check and attach livestream function. TypeError: Cannot read properties of undefined (reading 'map')
    at DoorbellCameraAccessory.getCameraConfig (/homebridge/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:159:44)
    at new CameraAccessory (/homebridge/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:48:34)
    at new DoorbellCameraAccessory (/homebridge/node_modules/homebridge-eufy-security/src/accessories/DoorbellCameraAccessory.ts:29:5)
    at EufySecurityPlatform.register_accessory (/homebridge/node_modules/homebridge-eufy-security/src/platform.ts:393:13)
    at EufySecurityPlatform.discoverDevices (/homebridge/node_modules/homebridge-eufy-security/src/platform.ts:300:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-eufy-security/src/platform.ts:150:7)
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Doorbell Looks like not compatible with isEnabled or this has been disabled within configuration
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Doorbell Looks like not compatible with isMotionDetectionEnabled or this has been disabled within configuration
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Doorbell Looks like not compatible with DeviceLight
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Terrace Doorbell  raise error to check and attach livestream function. TypeError: Cannot read properties of undefined (reading 'map')
    at DoorbellCameraAccessory.getCameraConfig (/homebridge/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:159:44)
    at new CameraAccessory (/homebridge/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:48:34)
    at new DoorbellCameraAccessory (/homebridge/node_modules/homebridge-eufy-security/src/accessories/DoorbellCameraAccessory.ts:29:5)
    at EufySecurityPlatform.register_accessory (/homebridge/node_modules/homebridge-eufy-security/src/platform.ts:393:13)
    at EufySecurityPlatform.discoverDevices (/homebridge/node_modules/homebridge-eufy-security/src/platform.ts:300:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-eufy-security/src/platform.ts:150:7)
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Terrace Doorbell  Looks like not compatible with isEnabled or this has been disabled within configuration
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Terrace Doorbell  Looks like not compatible with isMotionDetectionEnabled or this has been disabled within configuration
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Terrace Doorbell  Looks like not compatible with DeviceLight
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Exterior North has no battery
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Exterior North Looks like not compatible with isEnabled or this has been disabled within configuration
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Exterior North Looks like not compatible with isMotionDetectionEnabled or this has been disabled within configuration
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Exterior West has no battery
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Exterior West Looks like not compatible with isEnabled or this has been disabled within configuration
[3/29/2022, 11:38:20 AM] [homebridge-eufy-security] Exterior West Looks like not compatible with isMotionDetectionEnabled or this has been disabled within configuration
[3/29/2022, 11:39:36 AM] [homebridge-eufy-security] Exterior North handleMotionDetectedGet Wrong return value
[3/29/2022, 11:39:36 AM] [homebridge-eufy-security] Exterior West handleMotionDetectedGet Wrong return value
[3/29/2022, 11:40:56 AM] [homebridge-eufy-security] Exterior North handleMotionDetectedGet Wrong return value
[3/29/2022, 11:40:56 AM] [homebridge-eufy-security] Exterior West handleMotionDetectedGet Wrong return value
[3/29/2022, 1:51:46 PM] [homebridge-eufy-security] Exterior North handleMotionDetectedGet Wrong return value
[3/29/2022, 1:51:46 PM] [homebridge-eufy-security] Exterior West handleMotionDetectedGet Wrong return value

**Comment by kisonho** [comment]
I got the same problems again after it automatically repaired after some days. I checked the detailed message, and found that this actually caused by capture verification since there was another message followed by the `Failed to request` error saying `Captcha verification received`.

**Comment by lenoxys** [comment]
Click on plug-in setting you will be prompted for the captcha.

**Comment by kisonho** [comment]
> Click on plug-in setting you will be prompted for the captcha.

I opened the settings and reentered the password, but got the reply message `Failed to request` along with `Captcha verification received`. There is no captcha verification popped out. Instead, the UI still shows a `Wrong username and password` warning.

**Comment by lenoxys** [comment]
With the latest beta ?
