### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'map') in v1.1.1-beta.38

### ISSUE THREAD

**Issue by dewoert** [samemory/homebridge-eufy-security#373]
### What happened?

Updated to v1.1.1-beta.38, and recieving following errors now:
```
[29/03/2022, 18:04:46] Registering platform 'homebridge-eufy-security.EufySecurity'
[29/03/2022, 18:04:46] [homebridge-eufy-security] Loaded homebridge-eufy-security v1.1.1-beta.38 child bridge successfully
[29/03/2022, 18:04:46] Loaded 2 cached accessories from cachedAccessories.0EBB5A38298C.
[29/03/2022, 18:04:47] [homebridge-eufy-security] Country set: NL
[29/03/2022, 18:04:47] [homebridge-eufy-security] Unbridge set: false
[29/03/2022, 18:04:47] [homebridge-eufy-security] Finished initializing Eufy Security Platform
[29/03/2022, 18:04:47] Homebridge v1.4.0 (HAP v0.10.0) (homebridge-eufy-security) is running on port 53515.
TypeError: Cannot read properties of undefined (reading 'map')
    at DoorbellCameraAccessory.getCameraConfig (/usr/local/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:158:44)
    at new CameraAccessory (/usr/local/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:40:30)
    at new DoorbellCameraAccessory (/usr/local/lib/node_modules/homebridge-eufy-security/src/accessories/DoorbellCameraAccessory.ts:29:5)
    at EufySecurityPlatform.register_accessory (/usr/local/lib/node_modules/homebridge-eufy-security/src/platform.ts:393:13)
    at EufySecurityPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-eufy-security/src/platform.ts:300:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-eufy-security/src/platform.ts:150:7)
[29/03/2022, 18:04:52] [homebridge-eufy-security] Child bridge process ended
[29/03/2022, 18:04:52] [homebridge-eufy-security] Process Ended. Code: 1, Signal: null
[29/03/2022, 18:04:59] [homebridge-eufy-security] Restarting Process...
```

### Device Type

Doorbell (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[29/03/2022, 18:04:46] Registering platform 'homebridge-eufy-security.EufySecurity'
[29/03/2022, 18:04:46] [homebridge-eufy-security] Loaded homebridge-eufy-security v1.1.1-beta.38 child bridge successfully
[29/03/2022, 18:04:46] Loaded 2 cached accessories from cachedAccessories.0EBB5A38298C.
[29/03/2022, 18:04:47] [homebridge-eufy-security] Country set: NL
[29/03/2022, 18:04:47] [homebridge-eufy-security] Unbridge set: false
[29/03/2022, 18:04:47] [homebridge-eufy-security] Finished initializing Eufy Security Platform
[29/03/2022, 18:04:47] Homebridge v1.4.0 (HAP v0.10.0) (homebridge-eufy-security) is running on port 53515.
TypeError: Cannot read properties of undefined (reading 'map')
    at DoorbellCameraAccessory.getCameraConfig (/usr/local/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:158:44)
    at new CameraAccessory (/usr/local/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:40:30)
    at new DoorbellCameraAccessory (/usr/local/lib/node_modules/homebridge-eufy-security/src/accessories/DoorbellCameraAccessory.ts:29:5)
    at EufySecurityPlatform.register_accessory (/usr/local/lib/node_modules/homebridge-eufy-security/src/platform.ts:393:13)
    at EufySecurityPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-eufy-security/src/platform.ts:300:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-eufy-security/src/platform.ts:150:7)
[29/03/2022, 18:04:52] [homebridge-eufy-security] Child bridge process ended
[29/03/2022, 18:04:52] [homebridge-eufy-security] Process Ended. Code: 1, Signal: null
[29/03/2022, 18:04:59] [homebridge-eufy-security] Restarting Process...
```

**Comment by karesake** [comment]
Got the same.

**Comment by lenoxys** [comment]
Working on it

**Comment by MElkady** [comment]
I get the same.

**Comment by karesake** [comment]
Solved by manually adding the config posted by lenoxys. Unfortunately, RTSP doesn't really work. As with Camera UI, the stream is no longer accessible after a few minutes.

**Comment by lenoxys** [comment]
this is solved. sorry for the inconvenience!
