### ISSUE TITLE
[Bug]: Nothing showing in Home

### ISSUE THREAD

**Issue by abuja86** [samemory/homebridge-eufy-security#384]
### What happened?

Closest I've gotten to having anything appearing in my home app was using the latest beta, but I still get the error attached.

### Device Type

Doorbell (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Mac OS X 11+ (Supported)

### Relevant log output

```shell
[homebridge-eufy-security] /usr/local/lib/node_modules/homebridge-eufy-security/homebridge-ui/server.js:67
      this.config['country'] = body.country ??= 'US';
                                            ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by lenoxys** [comment]
hello, 

Can you clear your browser cache ?
