### ISSUE TITLE
[Bug]: Settings UI doesn't open

### ISSUE THREAD

**Issue by MElkady** [samemory/homebridge-eufy-security#387]
### What happened?

The UI to change the plugin settings doesn't open. Clicking on the "Settings" button on the plugin's card in the Plugin page shows a dialog that has a loading indicator that keeps loading forever.
I see there's an error in the log as well:

### Device Type

Doorbell (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[4/7/2022, 10:15:14 PM] [Homebridge UI] [homebridge-eufy-security] /usr/lib/node_modules/homebridge-eufy-security/homebridge-ui/server.js:68
      this.config['country'] = body.country ??= 'US';
                                            ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by lenoxys** [comment]
Hello,

Did you tried to clear your browser cache ?

**Comment by MElkady** [comment]
Hello @lenoxys ,
I see that error in the Homebridge logs, not in the browser's console. Clearing the browser's cache doesn't help.

**Comment by lenoxys** [comment]
And you’re using the latest beta ?

**Comment by MElkady** [comment]
I just upgraded to "homebridge-eufy-security v1.1.1-beta.51" & I still see the same error

**Comment by lenoxys** [comment]
> I just upgraded to "homebridge-eufy-security v1.1.1-beta.51" & I still see the same error

Need to dig on it this week

**Comment by lukestein** [comment]
I'm having the same issue. New installation on
```
OS	Raspbian GNU/Linux Buster (10)
Node.js Version	v14.19.3
User	homebridge
Storage Path	/var/lib/homebridge
Config Path	/var/lib/homebridge/config.json
Service Mode	Yes
```
![image](https://user-images.githubusercontent.com/44452336/171254929-1486bb6d-7fc0-4e95-8739-318fc441864d.png)

Clicking "Settings" gives a never-ending spinning gear.

Homebridge logs show
```
[31/05/2022, 14:04:45] [Homebridge UI] [homebridge-eufy-security] /usr/lib/node_modules/homebridge-eufy-security/homebridge-ui/server.js:107
      this.config['country'] = body.country ??= 'US';
                                            ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by schliemann** [comment]
This repo is deprecated. New repo is in the read me file.

**Comment by ngjespersen** [comment]
@lukestein Hi - I have the same problem with version 2.0.1, 2.0.0 and 1.0.8 - have you solved your problem?

**Comment by lukestein** [comment]
> @lukestein Hi - I have the same problem with version 2.0.1, 2.0.0 and 1.0.8 - have you solved your problem?

Hi @ngjespersen I found it worked for me with 2.0.1, but just checked and now I can no longer get access to the Settings page. However the plugin itself still works given I had already successfully gotten it set up. Ugh, sorry, and good luck!
