### ISSUE TITLE
Plugin doesn't load in Homebridge, puts Homebridge in infinite loading loop

### ISSUE THREAD

**Issue by njuart** [samemory/homebridge-eufy-security#56]
**Describe The Bug:**
Plugin doesn't load in Homebridge, puts Homebridge in infinite loading loop.

**To Reproduce:**
Just installed plugin and entered credentials.

**Expected behavior:**
Homebridge is loading with Eufy accessories.

**Logs:**

```
[6/26/2021, 10:04:25 PM] [EufySecurity] Eufy Guard Mode:  { value: 6, timestamp: 1624728259000 }
[6/26/2021, 10:04:25 PM] [EufySecurity] Eufy Guard Mode:  { value: 6, timestamp: 1624728259000 }
TypeError: this.eufyDevice.isEnabled is not a function
    at SecurityCameraAccessory.handleOnGet (/homebridge/node_modules/homebridge-eufy-security/src/securityCameraAccessory.ts:192:42)
    at On.emit (events.js:387:35)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
TypeError: this.eufyDevice.isEnabled is not a function
    at SecurityCameraAccessory.handleOnGet (/homebridge/node_modules/homebridge-eufy-security/src/securityCameraAccessory.ts:192:42)
    at On.emit (events.js:387:35)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
TypeError: this.eufyDevice.isMotionDetected is not a function
    at SecurityCameraAccessory.isMotionDetected (/homebridge/node_modules/homebridge-eufy-security/src/securityCameraAccessory.ts:160:46)
    at SecurityCameraAccessory.handleMotionDetectedGet (/homebridge/node_modules/homebridge-eufy-security/src/securityCameraAccessory.ts:170:37)
    at MotionDetected.emit (events.js:387:35)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at MotionDetected.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
TypeError: this.eufyDevice.isMotionDetected is not a function
    at SecurityCameraAccessory.isMotionDetected (/homebridge/node_modules/homebridge-eufy-security/src/securityCameraAccessory.ts:160:46)
    at SecurityCameraAccessory.handleMotionDetectedGet (/homebridge/node_modules/homebridge-eufy-security/src/securityCameraAccessory.ts:170:37)
    at MotionDetected.emit (events.js:387:35)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at MotionDetected.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
[6/26/2021, 10:04:25 PM] Got SIGTERM, shutting down Homebridge...
```

**Plugin Config:**

```json
"username": "*****",
"password": "*****",
"hkHome": 1,
"hkAway": 0,
"hkNight": 3,
"hkOff": 63,
"hkDisarmed": 6,
"platform": "EufySecurity"
```

**Environment:**

* **0.2.4**:
* **Homebridge Version**: 1.3.4
* **Node.js Version**: 14.17.1
* **NPM Version**: 7.19.0
* **Operating System**: Alpine Linux (3.12.7)

**Comment by njuart** [comment]
I've installed latest 0.2.5 version and unfortunately getting same errors in logs.
