### ISSUE TITLE
Plugin will not start after reinstallation new version

### ISSUE THREAD

**Issue by CM-UH** [samemory/homebridge-eufy-security#61]
I deinstall the "birkir" Eufy security pluging and update this plugin, now the plugin will not start anymore.
I get the message: "Cannot find module 'eufy-security-client"
I try to install this library (npm i eufy-security-client), but no success

> [30/06/2021, 18:22:54] ERROR LOADING PLUGIN homebridge-eufy-security:
[30/06/2021, 18:22:54] Error: Cannot find module 'eufy-security-client'
Require stack:
- /usr/local/lib/node_modules/homebridge-eufy-security/dist/securityEntrySensorAccessory.js
- /usr/local/lib/node_modules/homebridge-eufy-security/dist/platform.js
- /usr/local/lib/node_modules/homebridge-eufy-security/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-eufy-security/src/securityEntrySensorAccessory.ts:9:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
[30/06/2021, 18:22:54] ====================

Now I have no more ideas, please help!

**Comment by samemory** [comment]
Due to issues with the latest build, I have rolled back the latest NPM update. Please update the homebridge plugin again with the previous (now current) version v0.2.4. This should fix your issues.
