### ISSUE TITLE
Error with 1.2.4. Back to 1.2.3 works again...

### ISSUE THREAD

**Issue by Dominik-1980** [samemory/homebridge-eufy-security#82]
**Describe The Bug:**
For me the error I reported in #57 still remains...

**Logs:**

```
[7/15/2021, 3:02:12 PM] [EufySecurity] Eufy Guard Mode:  { value: 1, timestamp: 1626336053000 }
[7/15/2021, 3:02:12 PM] [EufySecurity] Eufy Guard Mode:  { value: 1, timestamp: 1626336053000 }
(node:15747) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at SecurityCameraAccessory.handleMotionOnGet (/homebridge/node_modules/homebridge-eufy-security/src/securityCameraAccessory.ts:239:5)
    at On.emit (events.js:387:35)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15747) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15747) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15747) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at SecurityCameraAccessory.handleMotionOnGet (/homebridge/node_modules/homebridge-eufy-security/src/securityCameraAccessory.ts:239:5)
    at On.emit (events.js:387:35)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
(node:15747) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by Dominik-1980** [comment]
I found out, that the plugin is working, but on every status change the error shows up in the homebridge log.
Should I try to delete the cams and the homebase from the home bridge cache?
Is this safe without loosing something?

**Comment by lboue** [comment]
Hello

I am facing the same issue with homebridge-plugin-eufy-security@0.1.8:
```
[7/20/2021, 3:21:03 PM] ---
[7/20/2021, 3:21:04 PM] Loaded plugin: homebridge-plugin-eufy-security@0.1.8
[7/20/2021, 3:21:04 PM] Registering platform 'homebridge-plugin-eufy-security.EufySecurityHomebridgePlugin'
[7/20/2021, 3:21:04 PM] ---
...
(node:627) UnhandledPromiseRejectionWarning: Error: GCM-Register -> Error=PHONE_REGISTRATION_ERROR
    at PushRegisterService.<anonymous> (/homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-register.service.js:139:23)
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-register.service.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:627) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:627) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Regards

**Comment by schliemann** [comment]
Have you enabled detailed logging?

**Comment by lboue** [comment]
I just enabled 'enableDetailedLogging' and this is what i get in the logs. 
It seems that something goes wrong with the 'push token'.
```
[7/20/2021, 4:58:30 PM] [EufySecurityHomebridgePlugin] Initializing EufySecurityHomebridgePlugin platform...
[7/20/2021, 4:58:30 PM] [EufySecurityHomebridgePlugin] push client enabled
[7/20/2021, 4:58:30 PM] [EufySecurityHomebridgePlugin] credentials found. reusing them...
[7/20/2021, 4:58:31 PM] [EufySecurityHomebridgePlugin] failed to register push token Error: Request failed: https://security-app-eu.eufylife.com/v1/passport/login -> 100028 - Failed to request.
    at /homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:826) UnhandledPromiseRejectionWarning: Error: Request failed: https://security-app-eu.eufylife.com/v1/passport/login -> 100028 - Failed to request.
    at /homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:826) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:826) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[7/20/2021, 4:59:01 PM] [EufySecurityHomebridgePlugin] failed to confirm push token
[7/20/2021, 4:59:31 PM] [EufySecurityHomebridgePlugin] failed to confirm push token
```
Regards

**Comment by schliemann** [comment]
What credentials are you using? Have you created a guest account and use that? I think that is the preferred method.

**Comment by lboue** [comment]
Yes, I a using a guest account. I tried with eufy-security-ws but I have the same issue:

```
pi@raspberrypi:~/eufy-security-ws $ npx ts-node ./src/bin/server.ts -vvv
2021-07-21 10:43:46.111  DEBUG [undefined.constructor] Load previous login_hash: f5d924b6a991d13a4585253d40f9f175 
2021-07-21 10:43:46.144  DEBUG [src/lib/server.ts:340  EufySecurityServer.start] Starting server on port 3000 
2021-07-21 10:43:46.162  INFO [src/lib/server.ts:346  EufySecurityServer.start] Eufy Security server listening on port 3000 
2021-07-21 10:43:46.223  DEBUG [HTTPApi.authenticate] Authenticate and get an access token 
{
  token: null,
  tokenExpiration: null
}
2021-07-21 10:43:46.237  DEBUG [HTTPApi.request] Request: 
{
  method: 'post',
  endpoint: 'passport/login',
  baseUrl: 'https://mysecurity.eufylife.com/api/v1',
  token: null,
  data: {
    email: 'lud****************@gmail.com',
    password: '[***]'
  },
  headers: {
    app_version: 'v2.8.0_887',
    os_type: 'android',
    os_version: '30',
    phone_model: 'EUFYCLIENT',
    country: 'US',
    language: 'en',
    openudid: '5ab689bf2d1fd10',
    uid: '',
    net_type: 'wifi',
    mnc: '02',
    mcc: '262',
    sn: '***********',
    Model_type: 'PHONE',
    timezone: 'GMT+02:00'
  }
}
2021-07-21 10:43:47.127  DEBUG [HTTPApi.authenticate] Response: 
{
  code: 0,
  msg: 'ok',
  data: {
    user_id: '****************************',
    email: 'lud****************@gmail.com',
    nick_name: 'lud***',
    auth_token: '9d26e141270535bda2b5e958a7387f4ab2ac1c83e0433cd3',
    token_expires_at: 1629456226,
    avatar: '',
    invitation_code: 'e893379bfd7dbaa91612',
    inviter_code: '',
    verify_code_url: '',
    mac_addr: '',
    domain: 'security-app-eu.eufylife.com',
    ab_code: 'FR',
    geo_key: '****************************',
    privilege: 0,
    phone: '',
    phone_code: '',
    params: null,
    trust_list: []
  }
}
2021-07-21 10:43:47.134  INFO [HTTPApi.authenticate] Switching to another API_BASE (https://security-app-eu.eufylife.com/v1) and get new token. 
2021-07-21 10:43:47.138  DEBUG [EufySecurity.connect] Renew token 
2021-07-21 10:43:47.142  DEBUG [HTTPApi.authenticate] Authenticate and get an access token 
{
  token: null,
  tokenExpiration: null
}
2021-07-21 10:43:47.146  DEBUG [HTTPApi.request] Request: 
{
  method: 'post',
  endpoint: 'passport/login',
  baseUrl: 'https://security-app-eu.eufylife.com/v1',
  token: null,
  data: {
    email: 'lud****************@gmail.com',
    password: '[***]'
  },
  headers: {
    app_version: 'v2.8.0_887',
    os_type: 'android',
    os_version: '30',
    phone_model: 'EUFYCLIENT',
    country: 'US',
    language: 'en',
    openudid: '5ab689bf2d1fd10',
    uid: '',
    net_type: 'wifi',
    mnc: '02',
    mcc: '262',
    sn: '***********',
    Model_type: 'PHONE',
    timezone: 'GMT+02:00'
  }
}
2021-07-21 10:43:47.271  DEBUG [HTTPApi.authenticate] Response: 
{
  code: 100028,
  msg: 'Failed to request.'
}
2021-07-21 10:43:47.276  ERROR [HTTPApi.authenticate] Response code not ok 
{
  code: 100028,
  msg: 'Failed to request.'
}
2021-07-21 10:43:47.280  ERROR [EufySecurity.connect] Token error 
```

**Comment by schliemann** [comment]
@lboue Then it must be in the client library or on Eufys end. Try creating an issue `[here](https://github.com/bropat/eufy-security-client/issues)`

**Comment by schliemann** [comment]
@Dominik-1980 I think this error has been described in a couple of the already open issues. Please consider closing this issue.

**Comment by lenoxys** [comment]
Looks like you have enabled two factor authentication. unfortunately, we don't support this yet. I suggest to create a new account dedicated for homebridge and link to the primary one.
