### ISSUE TITLE
Indoor 2k camera no Motion setting

### ISSUE THREAD

**Issue by xraywinedrinker** [samemory/homebridge-eufy-security#92]
The current version, 0.2.12 does not allow the indoor 2k camera to turn on/off motion settings. Earlier versions, I think with 0.1.4 motion detection could be turned on/off but now it’s always on.

Is it possible to bring that feature back to the current version?

**Comment by schliemann** [comment]
Does the log show any errors?

**Comment by xraywinedrinker** [comment]
[7/26/2021, 7:35:35 PM] [homebridge-eufy-security] Family room Handle Motion Sensor:  --  false
[7/26/2021, 7:35:36 PM] [homebridge-eufy-security] Driveway Handle Motion Sensor:  --  false
[7/26/2021, 7:35:36 PM] [homebridge-eufy-security] Driveway Handle Current battery level:  --  93
[7/26/2021, 7:35:36 PM] [homebridge-eufy-security] Driveway Handle Switch:  --  true
[7/26/2021, 7:35:36 PM] [homebridge-eufy-security] Backyard Handle Motion Sensor:  --  false
[7/26/2021, 7:35:36 PM] [homebridge-eufy-security] Backyard Handle Current battery level:  --  100
[7/26/2021, 7:35:36 PM] [homebridge-eufy-security] Backyard Handle Switch:  --  false
[7/26/2021, 7:35:36 PM] [homebridge-eufy-security] Front Door Handle Motion Sensor:  --  false
[7/26/2021, 7:35:36 PM] [homebridge-eufy-security] Front Door Handle Current battery level:  --  92
[7/26/2021, 7:35:36 PM] [homebridge-eufy-security] Front Door Handle Switch:  --  true
[7/26/2021, 7:35:36 PM] [homebridge-eufy-security] Front Yard Handle Motion Sensor:  --  false
[7/26/2021, 7:35:36 PM] [homebridge-eufy-security] Front Yard Handle Current battery level:  --  94
[7/26/2021, 7:35:36 PM] [homebridge-eufy-security] Front Yard Handle Switch:  --  false
[7/26/2021, 7:35:36 PM] [homebridge-eufy-security] HomeBase Handle Current System state:  --  0
[7/26/2021, 7:35:36 PM] [homebridge-eufy-security] Kitchen Handle Motion Sensor:  --  false
[7/26/2021, 7:35:36 PM] [homebridge-eufy-security] Office Handle Motion Sensor:  --  false
(node:3646) UnhandledPromiseRejectionWarning: TypeError: this.eufyDevice.isEnabled is not a function
    at CameraAccessory.handleOnGet (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:209:42)
    at On.emit (events.js:327:22)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3646) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3646) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3646) UnhandledPromiseRejectionWarning: TypeError: this.eufyDevice.isEnabled is not a function
    at CameraAccessory.handleOnGet (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:209:42)
    at On.emit (events.js:327:22)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
(node:3646) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:3646) UnhandledPromiseRejectionWarning: TypeError: this.eufyDevice.isEnabled is not a function
    at CameraAccessory.handleOnGet (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:209:42)
    at On.emit (events.js:327:22)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at On.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
(node:3646) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:3646) UnhandledPromiseRejectionWarning: TypeError: this.eufyDevice.isMotionDetected is not a function
    at CameraAccessory.isMotionDetected (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:178:46)
    at CameraAccessory.handleMotionDetectedGet (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:188:37)
    at MotionDetected.emit (events.js:327:22)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at MotionDetected.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
(node:3646) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:3646) UnhandledPromiseRejectionWarning: TypeError: this.eufyDevice.isMotionDetected is not a function
    at CameraAccessory.isMotionDetected (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:178:46)
    at CameraAccessory.handleMotionDetectedGet (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:188:37)
    at MotionDetected.emit (events.js:327:22)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at MotionDetected.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
(node:3646) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:3646) UnhandledPromiseRejectionWarning: TypeError: this.eufyDevice.isMotionDetected is not a function
    at CameraAccessory.isMotionDetected (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:178:46)
    at CameraAccessory.handleMotionDetectedGet (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:188:37)
    at MotionDetected.emit (events.js:327:22)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at MotionDetected.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
(node:3646) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)

**Comment by lenoxys** [comment]
Should be fixed #93
